# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Insta_app', '0006_auto_20170729_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Insta_app.UserProfile'),
        ),
    ]
