# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insta_app', '0011_auto_20170730_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesmodel',
            name='post',
        ),
        migrations.DeleteModel(
            name='CategoriesModel',
        ),
    ]
