# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0002_auto_20170723_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtable',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
